name: CI Pipeline

on:
  push:

jobs:
    test:
        runs-on: ubuntu_latest

        steps:
            - name: Telecharger le code
              uses: actions/checkout@v3
            - name: Intaller Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Installer pytest
              run: pip install pytest
            - name: Lancer les tests
              run: pytest